/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

goog.provide('proto.CameraStream');
goog.provide('proto.CameraStream.CameraType');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');


/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.CameraStream = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.CameraStream, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.CameraStream.displayName = 'proto.CameraStream';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.CameraStream.prototype.toObject = function(opt_includeInstance) {
  return proto.CameraStream.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.CameraStream} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.CameraStream.toObject = function(includeInstance, msg) {
  var f, obj = {
    streamCamera: jspb.Message.getFieldWithDefault(msg, 1, false),
    cameraType: jspb.Message.getFieldWithDefault(msg, 2, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.CameraStream}
 */
proto.CameraStream.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.CameraStream;
  return proto.CameraStream.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.CameraStream} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.CameraStream}
 */
proto.CameraStream.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setStreamCamera(value);
      break;
    case 2:
      var value = /** @type {!proto.CameraStream.CameraType} */ (reader.readEnum());
      msg.setCameraType(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.CameraStream.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.CameraStream.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.CameraStream} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.CameraStream.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getStreamCamera();
  if (f) {
    writer.writeBool(
      1,
      f
    );
  }
  f = message.getCameraType();
  if (f !== 0.0) {
    writer.writeEnum(
      2,
      f
    );
  }
};


/**
 * @enum {number}
 */
proto.CameraStream.CameraType = {
  UNSET: 0,
  FRONT: 1,
  CABIN: 2,
  REAR: 3,
  LEFT_SIDE: 4,
  RIGHT_SIDE: 5,
  FRONT_LEFT: 6,
  FRONT_RIGHT: 7
};

/**
 * optional bool stream_camera = 1;
 * Note that Boolean fields may be set to 0/1 when serialized from a Java server.
 * You should avoid comparisons like {@code val === true/false} in those cases.
 * @return {boolean}
 */
proto.CameraStream.prototype.getStreamCamera = function() {
  return /** @type {boolean} */ (jspb.Message.getFieldWithDefault(this, 1, false));
};


/** @param {boolean} value */
proto.CameraStream.prototype.setStreamCamera = function(value) {
  jspb.Message.setProto3BooleanField(this, 1, value);
};


/**
 * optional CameraType camera_type = 2;
 * @return {!proto.CameraStream.CameraType}
 */
proto.CameraStream.prototype.getCameraType = function() {
  return /** @type {!proto.CameraStream.CameraType} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/** @param {!proto.CameraStream.CameraType} value */
proto.CameraStream.prototype.setCameraType = function(value) {
  jspb.Message.setProto3EnumField(this, 2, value);
};


