/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

goog.provide('proto.SendCommandRequest');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');
goog.require('proto.CommandQueueWrapper');


/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.SendCommandRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.SendCommandRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.SendCommandRequest.displayName = 'proto.SendCommandRequest';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.SendCommandRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.SendCommandRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.SendCommandRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.SendCommandRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    vehicleUuid: jspb.Message.getFieldWithDefault(msg, 1, ""),
    commandWrapper: (f = msg.getCommandWrapper()) && proto.CommandQueueWrapper.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.SendCommandRequest}
 */
proto.SendCommandRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.SendCommandRequest;
  return proto.SendCommandRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.SendCommandRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.SendCommandRequest}
 */
proto.SendCommandRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setVehicleUuid(value);
      break;
    case 3:
      var value = new proto.CommandQueueWrapper;
      reader.readMessage(value,proto.CommandQueueWrapper.deserializeBinaryFromReader);
      msg.setCommandWrapper(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.SendCommandRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.SendCommandRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.SendCommandRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.SendCommandRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getVehicleUuid();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getCommandWrapper();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      proto.CommandQueueWrapper.serializeBinaryToWriter
    );
  }
};


/**
 * optional string vehicle_uuid = 1;
 * @return {string}
 */
proto.SendCommandRequest.prototype.getVehicleUuid = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.SendCommandRequest.prototype.setVehicleUuid = function(value) {
  jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional CommandQueueWrapper command_wrapper = 3;
 * @return {?proto.CommandQueueWrapper}
 */
proto.SendCommandRequest.prototype.getCommandWrapper = function() {
  return /** @type{?proto.CommandQueueWrapper} */ (
    jspb.Message.getWrapperField(this, proto.CommandQueueWrapper, 3));
};


/** @param {?proto.CommandQueueWrapper|undefined} value */
proto.SendCommandRequest.prototype.setCommandWrapper = function(value) {
  jspb.Message.setWrapperField(this, 3, value);
};


proto.SendCommandRequest.prototype.clearCommandWrapper = function() {
  this.setCommandWrapper(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.SendCommandRequest.prototype.hasCommandWrapper = function() {
  return jspb.Message.getField(this, 3) != null;
};


