/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

goog.provide('proto.ThirdPartyCommand');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');
goog.require('proto.Garage');


/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.ThirdPartyCommand = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, proto.ThirdPartyCommand.oneofGroups_);
};
goog.inherits(proto.ThirdPartyCommand, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.ThirdPartyCommand.displayName = 'proto.ThirdPartyCommand';
}
/**
 * Oneof group definitions for this message. Each group defines the field
 * numbers belonging to that group. When of these fields' value is set, all
 * other fields in the group are cleared. During deserialization, if multiple
 * fields are encountered for a group, only the last value seen will be kept.
 * @private {!Array<!Array<number>>}
 * @const
 */
proto.ThirdPartyCommand.oneofGroups_ = [[1]];

/**
 * @enum {number}
 */
proto.ThirdPartyCommand.CommandCase = {
  COMMAND_NOT_SET: 0,
  GARAGE: 1
};

/**
 * @return {proto.ThirdPartyCommand.CommandCase}
 */
proto.ThirdPartyCommand.prototype.getCommandCase = function() {
  return /** @type {proto.ThirdPartyCommand.CommandCase} */(jspb.Message.computeOneofCase(this, proto.ThirdPartyCommand.oneofGroups_[0]));
};



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.ThirdPartyCommand.prototype.toObject = function(opt_includeInstance) {
  return proto.ThirdPartyCommand.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.ThirdPartyCommand} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.ThirdPartyCommand.toObject = function(includeInstance, msg) {
  var f, obj = {
    garage: (f = msg.getGarage()) && proto.Garage.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.ThirdPartyCommand}
 */
proto.ThirdPartyCommand.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.ThirdPartyCommand;
  return proto.ThirdPartyCommand.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.ThirdPartyCommand} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.ThirdPartyCommand}
 */
proto.ThirdPartyCommand.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.Garage;
      reader.readMessage(value,proto.Garage.deserializeBinaryFromReader);
      msg.setGarage(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.ThirdPartyCommand.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.ThirdPartyCommand.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.ThirdPartyCommand} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.ThirdPartyCommand.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getGarage();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.Garage.serializeBinaryToWriter
    );
  }
};


/**
 * optional Garage garage = 1;
 * @return {?proto.Garage}
 */
proto.ThirdPartyCommand.prototype.getGarage = function() {
  return /** @type{?proto.Garage} */ (
    jspb.Message.getWrapperField(this, proto.Garage, 1));
};


/** @param {?proto.Garage|undefined} value */
proto.ThirdPartyCommand.prototype.setGarage = function(value) {
  jspb.Message.setOneofWrapperField(this, 1, proto.ThirdPartyCommand.oneofGroups_[0], value);
};


proto.ThirdPartyCommand.prototype.clearGarage = function() {
  this.setGarage(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.ThirdPartyCommand.prototype.hasGarage = function() {
  return jspb.Message.getField(this, 1) != null;
};


